### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by wissehes** [MrJacz/discord.js-lavalink#178]
Hi, I just updated your module and now I'm getting this error when im trying to play something:
```TypeError: Cannot read property 'get' of undefined
    at PlayerManager.sendWS (/Users/e/Documents/Code/skeppy-bot/node_modules/discord.js-lavalink/dist/lib/PlayerManager.js:135:48)
    at PlayerManager.join (/Users/e/Documents/Code/skeppy-bot/node_modules/discord.js-lavalink/dist/lib/PlayerManager.js:41:14)
    at /Users/e/Documents/Code/skeppy-bot/commands/play.js:165:37
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

this is my code:
```js
    var theHost = getIdealHost(bot, message.guild.region);
    const player = await bot.player.join({
      guild: message.guild.id,
      channel: message.member.voiceChannelID,
      host: theHost
    });
    bot.execQueue(message, queue, player, true);
  }
```

**Comment by Ashutosh-3601** [comment]
In v3, PlayerManager is changed. That is, PlayerManager isn't collection anymore, and hence you can't use `.get()` on it. 
Instead PlayerManager.players is collection.
[Source](https://discordapp.com/channels/323779330033319941/562199981197361152/685255095646158882)

**Comment by wissehes** [comment]
But I'm not using `.get()` in that particular line, line 165 is `const player = await bot.player.join({`

**Comment by wissehes** [comment]
oh, I see what the error is. It's because I still have Discord.JS v11 and in `PlayerManager.js` it's using the v12 `client.guild.cache.get()`. I am gonna update my Discord.JS
