### ISSUE TITLE
[BUG] Music does not start

### ISSUE THREAD

**Issue by iamrunyard** [MrJacz/discord.js-lavalink#96]
I have a problem, the music does not start on linux ... Java version: 1.8.0_201 Build: 1.8.0_201-b09. The commands work but not the music ..

**Comment by MrJacz** [comment]
Are sure this is a bug with the library or a bug with lavalink?
it could also be your code. try the example file.

**Comment by iamrunyard** [comment]
Everything works fine ... Lavalink tells me that he has researched the music and started the music, but Discord nothing happens .. On my pc it works perfectly, but on the vps no ...

**Comment by iamrunyard** [comment]
I have exactly the same problem : https://github.com/MrJacz/discord.js-lavalink/issues/4

**Comment by MrJacz** [comment]
Please join [**the discord**](https://discord.gg/J8AqH4A)
I can further help there not on here spamming peoples emails as this is for legitimate bug reports. with reproduction steps

**Comment by LevitatingBusinessMan** [comment]
You closed this issue and #4 but it's an issue for me as well, and it's definitely a major bug. There's nothing to add to the bug report, it simply doesn't work. Your example doesn't even work. Could you please check if there is maybe an incompatibility with the newer versions of LavaLink or with discord.js or something similiar?

**Comment by MrJacz** [comment]
@LevitatingBusinessMan if you join the discord server like i said above, I can help you but i need reproduction steps other than "its a major bug"

**Comment by LevitatingBusinessMan** [comment]
@MrJacz Hey, thanks for the response, I am currently in the Discord.
